[project]
name = "telegram-popbot"
version = "0.1.0"
description = "Bot de Telegram para cultura pop com GPT e geração de conteúdo automatizado"
requires-python = ">=3.11"

dependencies = [
    "python-telegram-bot==20.7",
    "openai>=1.0.0"
]
