services:
  - type: web
    name: fastapi-groq-app
    env: python
    plan: free
    region: oregon
    autoDeploy: true
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --reload
    envVars:
      - key: GROQ_API_KEY
        fromEnv: GROQ_API_KEY
