render:

  services:
    - type: background
      name: telegram-bot
      env: python
      plan: free
      buildCommand: "pip install -r requirements.txt"
      startCommand: "python main.py"
      autoDeploy: true
